### ISSUE TITLE
NCBIM37

### ISSUE THREAD

**Issue by gmicevic** [hammerlab/topiary#47]
What is the --reference-name for mm9 (NCBIM37) ? Thank you.

**Comment by iskandr** [comment]
Hey @gmicevic, 

It looks like we only added GRCm38 to pyensembl (https://github.com/hammerlab/pyensembl/blob/master/pyensembl/species.py#L176), I'll try to fix that tomorrow. 

Sorry,
Alex

**Comment by gmicevic** [comment]
Great, that would help a lot. Thank you.

**Comment by iskandr** [comment]
Hey @gmicevic, 

It turns out that this hits an open problem in how we've been treating references: though the UCSC and Ensembl's references are similar they are not, unfortunately, identical. We've been chugging along by treating, for example, hg19 as GRCh37. I'm going to write a quick/dirty fix right now which treats mm9 as GRCm37 but there will be differences in terms of names for unplaced or alternate contigs.

**Comment by iskandr** [comment]
@gmicevic Do you mind updating your copy of `varcode`, `gtfparse`, & `pyensembl` and trying again? You'll have to first run `pyensembl install --release 67 --species mouse`.
